services:
  mongo:
    image: arm64v8/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.prod
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
