services:
  mongo:
    image: arm64v8/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

volumes:
  mongo-data:
